{% set name = "xugrid" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d8862e53044314f463aba54bd21977252930acf9d0e618b53bf27f354d5d582

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask
    - geopandas
    - numba >=0.50
    - numba_celltree
    - numpy
    - pandas
    - pooch
    - scipy
    - shapely >=2.0
    - xarray >=0.15

test:
  imports:
    - xugrid

about:
  home: https://github.com/deltares/xugrid
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Xarray and unstructured grids
  description: |
    Xarray extension to work with 2D unstructured grids, for data and topology
    stored according to UGRID conventions. Processing structured data with
    xarray is convenient and efficient. The goal of xugrid to extend this ease
    to unstructured grids.
  doc_url: https://deltares.github.io/xugrid/
  dev_url: https://github.com/deltares/xugrid

extra:
  recipe-maintainers:
    - HendrikKok
    - luitjansl
    - Huite
    - JoerivanEngelen
    - visr
